name: C++ Windows CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -S . -B build -A Win32

    - name: Build
      run: cmake --build build --config Release

    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: compiled-build
        path: |
          build/Release/
